server:
  port: 8085

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loanrepayments
    username: postgres
    password: PenangTrang!
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect